repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.0.0
    hooks:
      - id: sqlfluff-lint
        args: ["--dialect", "snowflake"]
      - id: sqlfluff-fix
        args: ["--dialect", "snowflake"]
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.7
    hooks:
      - id: check-model-has-all-columns
        args: ["--exclude=dbt_project_evaluator*"]
      - id: check-model-columns-have-desc
        args: ["--exclude=dbt_project_evaluator*"]
      - id: check-model-has-description
        args: ["--exclude=dbt_project_evaluator*"]
      - id: check-model-has-tests
        args: ["--exclude=dbt_project_evaluator*"]
      - id: check-source-columns-have-desc
        args: ["--exclude=dbt_project_evaluator*"]
      - id: check-source-table-has-description
        args: ["--exclude=dbt_project_evaluator*"]
